"""user_add

Revision ID: 1950595eb7ee
Revises: b61eb6840ab3
Create Date: 2023-08-06 18:08:59.178345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1950595eb7ee'
down_revision = 'b61eb6840ab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('Contacts', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Contacts', 'Users', ['user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Contacts', type_='foreignkey')
    op.drop_column('Contacts', 'user')
    op.drop_table('Users')
    # ### end Alembic commands ###
