"""user_update_add_confirmed

Revision ID: abcd45eae5ca
Revises: 1c0041ae36c1
Create Date: 2023-08-14 21:26:46.809847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcd45eae5ca'
down_revision = '1c0041ae36c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'confirmed')
    # ### end Alembic commands ###
