"""user_update_add_avatar_column

Revision ID: ad954748e8af
Revises: abcd45eae5ca
Create Date: 2023-08-15 22:03:41.895015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad954748e8af'
down_revision = 'abcd45eae5ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'avatar')
    # ### end Alembic commands ###
